### ISSUE TITLE
Mesh improvements

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#10]
Hi Tushar,

your next task will be to make the mesh of the base case more suitable for buffet simulations. I suggest the following changes for a start:
- create a workflow without the execution of *restore0Dir*, the second *decomposePar*, and *rhoPimpleFoam* (only meshing)
- change the workflow to use 4 instead of 2 processes
- in the **snappyHexMeshDict** ([reference](https://www.openfoam.com/documentation/guides/latest/doc/guide-meshing-snappyhexmesh-castellation.html#sec-castellation-refinementRegions))
  - increase the surface refinement to reduce the y-plus value
  - add more surface layers to reach a y-plus value close to one (you computed a theoretical estimate)
  - add distance-based refinement to increase the region refinement close to the airfoil
  - add a refinement box to increase the wake resolution
  - add a refinement box to increase the resolution around the shock

Suggestion: initially, be moderate the changes to see how meshing time and memory consumption are affected be the different meshing parameters.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thank you.
Instructions noted. I will get back to you as soon as possible.


Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I have made the necessary changes in the files mentioned by you in the instructions.
Do I need to run the simulation based on these changes on Phoenix similar to what I did in the last issue? or shall I show these changes to you and then start running the simulation? I made changes as per my capacity of what I understood taking reference of the OpenFoam documentation.


Thank you.

Best regards,
Tushar
Also, please confirm where can I observe the computation time required for simulation - 
_log.rhoPimpleFoam_ right?

**Comment by Tushargh29** [comment]
Hello Sir,

I have made the necessary changes in the files mentioned by you in the instructions.
Do I need to run the simulation based on these changes on Phoenix similar to what I did in the last issue? or shall I show these changes to you and then start running the simulation? I made changes as per my capacity of what I understood taking reference of the OpenFoam documentation.


Also, please confirm where can I observe the computation time required for simulation -
_log.rhoPimpleFoam_ file right?


Thank you.

Best regards,
Tushar

**Comment by darshan315** [comment]
Hi Tushar,
- Time: In `log.rhoPimpleFoam` at every iteration of PISO loop convergence, you can find `execution time` and `clock time`. PimpleFoam performs summations of that time for a particular case. The time for last iteration would be the total time of a simulation.

Bests,
Darshan.

**Comment by AndreWeiner** [comment]
Hi Tushar,
please, try to perform the meshing on the cluster. If things don't work out initially, check the log files, especially for the apps with changed settings. Start easy and try to make one change at a time.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Please have a look on the mesh. I have made some mesh refinement changes based on the given instructions.

I observed yPlus value around **2.69**

Rest we can discuss in tomorrow's meeting.

Thank you.
![ssss](https://user-images.githubusercontent.com/71929988/100159937-f84e4b80-2eae-11eb-8b4b-3acdb41943cc.png)

**Comment by Tushargh29** [comment]
Hello Sir,
I implemented the changes suggested by you in today's meeting.
Let me know your feedback. I can see the _region refinement boxes_ in the form of mesh also _distance based airfoil region_ mesh. But I am not sure about _wakeBox_ mesh region as I cannot see it clearly.
![A1](https://user-images.githubusercontent.com/71929988/100276820-6a339d00-2f62-11eb-9d23-8f11ab98de32.png)
![A2](https://user-images.githubusercontent.com/71929988/100276823-6d2e8d80-2f62-11eb-9dec-4a501d58bb70.png)
![A3](https://user-images.githubusercontent.com/71929988/100276825-6ef85100-2f62-11eb-906b-8eec0bf3984e.png)
![A4](https://user-images.githubusercontent.com/71929988/100276830-71f34180-2f62-11eb-914e-ee66688e838e.png)
![A5](https://user-images.githubusercontent.com/71929988/100276834-74559b80-2f62-11eb-8b96-08f1f81c29c9.png)
![A6](https://user-images.githubusercontent.com/71929988/100276842-76b7f580-2f62-11eb-8646-fbd0eb55617a.png)






Nevertheless, suggest me something if needed, if this is okay then I can modify the refinement levels to get close to 1.
Currently, with this configuration I am getting _yPlus_ equals to **5.16**.

Thank you.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
the refinement boxes and the surface distance-based refinement don't seem to have the wanted effect yet. The refinement regions should look somewhat like sketched here:
![naca_mesh_ref_zones](https://user-images.githubusercontent.com/8482575/100323998-e069eb00-2fc6-11eb-8e18-11dc03a6b01a.png)

One important note: **the mesh is scaled by a factor of 0.18352 after the meshing**. Therefore, you have to define the refinement regions according to the unscaled mesh. The chord length of the unscaled airfoil is exactly one.
 
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

I understood and will get back to you with the update soon.

Thanks.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

If we are scaling the _wakeBox_ and _shockBox_ by the scaling factor of 0.18352 then we also need to scale the main _refinementBox_ with this value right?

Please let me know.

Thanks 

Tushar

**Comment by AndreWeiner** [comment]
The *refinementBox* entry is already properly set up.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Sure, understood.

Thanks.

Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I tried altering the dimensions of both _wakeBox_ and _shockBox_ and scaling them with the factor 0.18352.

But I noticed that somehow only _airfoil_ section is getting implemented and the in the _regionRefinement_ section the _wakeBox_ and _shockBox_ implementation is skipped so that everytime I am getting the same result in paraview.

I am attaching the screenshot of my geometry section including the dimensions of all the boxes.

Please suggest.

Thank you.

Regards,
Tushar
![Screenshot from 2020-12-02 18-19-04](https://user-images.githubusercontent.com/71929988/100908205-8936af80-34cb-11eb-893f-272240c0f157.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
- compare the entries for *refinementBox* and *wakeBox*: the type should be ~~**box** and not **searchableBox**~~ searchableBox and not box according to the [documentation](https://openfoam.com/documentation/guides/latest/doc/guide-meshing-snappyhexmesh-geometry.html); in the future, check the log-file of *snappyHexMesh*; certainly there was a warning because the type you specified does not exist
- make sure that you clean up the case before you restart the simulation
- the boxes are too large currently

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Actually the same results I was getting with the type - box, I just thought I should give a try with what they included in the Openfoam documentation. Nevertheless, I will try these instructions, reduce the boxes and see what happens.

I will let you know.

Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
I updated my last comment above. The type might not have been the problem. Try changing the following entries:
```
// old values
    maxLocalCells 100000;
    maxGlobalCells 2000000;
// suggested new values
    maxLocalCells 2000000;
    maxGlobalCells 8000000;
```
Be careful not to set the refinement levels to a too high value. If that doesn't work, please send me the log-file of snappy.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Sure, I will try this and let you know.
Thanks.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I simply followed the instruction given by you in the issue taskpoints.
I implemented following steps:

1. I created the workflow only for meshing in which i made changes in the _runCase_ file where I excluded the execution _restore0Dir_, the second _decomposePar_, and _rhoPimpleFoam_.

2. I changes number of processors from 2 to 4 where I changed the number of subdomains in both the _decomposeParDict_.

3. I made changes in the jobscript and change in the _runCase_ command for parallel execution of MPI i.e (_-np 4_)

4. Then for the surface and region refinement I made the changes in the _transonic_shock_buffet/test_cases/naca0012-34-base/snappyHexMeshDict_ .
a. Increased _refinementSurfaces_ level (7 7).
b. Added _nSurfaceLayers 8;_
c. Added _airfoil_, _wakeBox_, _shockBox_ in the _refinementRegions_ also included in the _geometry_ section as we discussed. I kept the refinement level _6_ for both _wakeBox_and _shockBox_


That is what I have followed till now.
I made changes in the _snappyHexmesh_ file located in the _testcase_ folder.
and analyzing the results from _post.foam_ file in the _run_ folder.

Please let me know your feedback.

Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,

- did you execute the meshing locally (on your laptop) or on the phoenix cluster?
- did you change the dictionary on the machine where you perform the meshing?
- did you change the dictionary in *test_cases/...* or in *run/...*?
- did you clean up old simulation data before restarting the meshing?

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,
1. I executed the meshing on Phoenix - pushing the changes to remote repo from local repo and _git pull_ in the transonic folder present on Phoenix then submitting the jobscript on Phoenix.

2. Yes I changed the _snappyHexMeshDict_ located in my machine _test_cases_ folder then after git push and pull commands I checked this dictionary in the cluster folder It was correctly showing the changes done earlier in the local file.

3. I am changing _snappyHexMeshDict_ in the _test_cases_ folder not in _run_ folder.

4. I am closing all the command terminals, folders and files before starting the new meshing on cluster.

Let me know your feedback sir.

Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
I'll create a pull request soon (have a look at the changes). I created some refinement boxes to start with, but the mesh still needs some improvements. Here is the workflow I used to check results:
- on the cluster:
  - remove old simulation in *run*
  - submit jobscript
- local:
  - copy data from phoenix for post-processing (using *scp* or *rsync*)

If you have questions, let me know. I'll also post some flow results here soon.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

I got the instructions. Could you please elaborate the last instruction about local repo (using scp or rsync), how does it relate to opening the _post.foam_ file in _Paraview_ for post processing? 

Rest of the things I understood.

Thanks.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

One more thing I noticed that you changed the workflow by uncommenting the execution of _restore0Dir_, the second _decomposePar_, and _rhoPimpleFoam_, does that mean this time I need to run the full simulation not just meshing on the cluster?

Please explain.
Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
I uncommented the solver execution to see how the new mesh affects the simulation results. You can uncomment them if you like.
[Here](https://cloudstorage.tu-braunschweig.de/getlink/fi31rXkCs4wnJfN65YXAs1KX/rsync_phoenix-2020-12-04_12.18.15.mp4) is an example of how to sync you local data with the cluster. I also attach a picture of the current mesh.
![mesh_refinement](https://user-images.githubusercontent.com/8482575/101158419-f82b1a00-362b-11eb-82fe-15952616076e.png)

Best, Andre

**Comment by AndreWeiner** [comment]
Hi Tushar,
I think it makes sense to add another small refinement box in the airfoil's wake:
![wakebox](https://user-images.githubusercontent.com/8482575/101159797-3cb7b500-362e-11eb-9463-88acb66646e5.png)
Best, Andre

**Comment by Tushargh29** [comment]
Thanks a lot sir.

Now I got the idea how to deal with _sync_ command.

Now the first thing I will do is uncommenting the solver execution, running only meshing on cluster then follow the sync commands, I should get the same result of mesh what you posted above.

Also I got the idea of adding another small wakeBox. I will implement after this.

I will get back to you soon.

Regards.
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I started making changes in the mesh refinement in order to make wall distance value close to the _yPlus_ = 1. I am making changes in the _nSurfaceLayers_ . Also, I added a small wake box at the trailing edge of the airfoil. I did meshing on cluster and implemented the steps given by you like clearing previous simulation data and _sync_ command.

But when I am opening the _post.foam_ file in Paraview, the _airfoil_ is missing surprisingly and I tried but could not rectify it. Could you please tell me why is this happening? 

Thank you.

Regards,
Tushar
![Screenshot from 2020-12-07 15-45-23](https://user-images.githubusercontent.com/71929988/101364892-5f063880-38a3-11eb-874a-efed7950efb8.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
whatever you changed, it was not successful. Try to make one small change at a time and ensure that always a correct mesh is created.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

I made a change in the _nSurfaceLayers_ by trial and error and finally at _nSurfaceLayers = 10_ I got the wall distance such that it's _yPlus_ value is coming around **1.945**

Now I will try to implement _small wakeBox_ in the mesh. I will let you know.

Thanks.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I implemented the small wake box behind the trailing edge of the airfoil called as _trailingBox_. Also, I checked whether or not the wall distance going close to _yPlus_ = 1. I am attaching the screenshot of the meshing including the small wake box. From this meshing configuration we are getting the _yPlus_ approximately **1**(something **1.4** or**1.6** varying the position of the cell on the surface) keeping _nSurfaceLayers_ = 10.

You please have a look on it, let me know what you think about the dimension of the box. Suggest me changes if needed.
Thank you.

Regards,
Tushar

![Screenshot from 2020-12-08 22-02-56](https://user-images.githubusercontent.com/71929988/101546946-d45c3100-39a9-11eb-9f51-7a9c6b0b98c3.png)

**Comment by Tushargh29** [comment]
Hello Sir,

1. I have implemented the smallest wake box in the close proximity of trailing edge of an airfoil with the refinement level of **6**.

2. I have performed the simulation for revised Mach number of **0.8** and analyzed the result in Paraview.

3. I think it has captured the buffet slightly but you please explain me what is happening there exactly in detail.

4. I am attaching the animation GIF below, please let me know your feedback on it.

5. Also, give me further instructions to follow. Actually, I am planning to start the simulations on two new cases: **Mach_0.82** and **Mach_0.84** simultaneously on Phoenix.

6. The simulation total time was somewhere around 1hour, so less compared to the base case. I think this is because of increased number of processors right? Please correct me if I am wrong.

Thank You.

Best Regards,
Tushar
![Mach_no_0 8_animation](https://user-images.githubusercontent.com/71929988/101812236-62a3f480-3b1b-11eb-9a0c-dabed391c7ba.gif)

**Comment by AndreWeiner** [comment]
Hi Tushar,
thanks for the data. Some comments:
- the refinement at the trailing edge must be set to a value larger than 6 to have any effect
- I think your simulation may have not completed; the runtime should be about 5-10 hours
- check the *log.rhoPimpleFoam* log file; jump to the end of the log file and check if the simulation completed successfully
- there is definitely no buffeting yet (probably because the simulation did not complete)
- did you check min and max of *y-plus*?
- for animations, try setting higher framerates in paraview

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

1. Yes, I will set that refinement level more than 6 and see what happens.

2. Yes, unfortunately the simulation is not completed it got terminated.

3. Yes, I checked the _log.rhoPimpleFoam_ it is showing this error message: **Primary job  terminated normally, but 1 process returned a non-zero exit code. Per user-direction, the job has been aborted. mpirun detected that one or more processes exited with non-zero status, thus causing the job to be terminated**. I search why this happened, I got the answer like this: **This error message usually occurs because the number of MPI processes you have requested (via the -np argument to mpirun) is not consistent with the number of worker processes required**. So should I change/increase the number of **-np 16** in the _runCase_ file? Please suggest.

4. No sign of buffet, okay understood.

5. Yes, I checked min of _yPlus_ is 1.514 and max of _yPlus_ is somewhere around 8-9 but if we select somewhat horizontal cell appropriately it is too close to 1.

6. Yes, I will set higher frames in Paraview.


Thank you.

Best regards,
Tushar
![simulatzion_bug](https://user-images.githubusercontent.com/71929988/101964781-d543cb80-3c12-11eb-924f-cc01855d4698.png)

**Comment by AndreWeiner** [comment]
Hi  Tushar,
the solver fails after a while, presumably because the mesh quality is not sufficient. Can you send me the case via TU-BS cloud storage?
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,
Sure, I have created a separated folder named as **my_case_Tushar** where I have uploaded  the zip file of the entire case in which please find this particular case named as **Mach_0.8** in the _testCases_ folder. I hope you were expecting the same from your above instruction.

Is this a major problem? Considering this much efforts in refining mesh still solver does not consider sufficient? Just asking
Please let me know what you think.
Thank you.


Best regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
I cannot open the archive. Neither *unzip* nor *tar* are able to open it. How did you create the archive?
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

I think now it should be proper.

Best,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
the instability in the solution very likely originates from the leading edge:
![temperature_field_nose](https://user-images.githubusercontent.com/8482575/102114531-9a23e100-3e3a-11eb-8fc4-e13617a372f4.png)
I am not yet sure what would be the best way to stabilize the solution. However, looking at yPlus, the mesh is still not fine enough at the airfoil surface:
![yplus_ma0 8](https://user-images.githubusercontent.com/8482575/102114692-cd667000-3e3a-11eb-8869-e98a350e3c10.png)
So, as a first step, keep refining the mesh close to the surface. First, I suggest increasing the surface refinement level by one. Maybe this change also stabilizes the solution.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thanks a lot. Yes, I will try to increase the surface refinement level and see what happens.
I will let you know soon.


Best,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I have uploaded the updated case of simulation on the cloud. Please have a look.
Thanks.

Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
after changing meshing parameters, you should first check if a proper mesh was created and then start the simulation. If you open the current mesh, you see that no surface layers were created. Moreover, most regions were not refined due to the enormous intermediate cell count (more than 9 Mio according to *log.snappyHexMesh*).
![airfoil_surface](https://user-images.githubusercontent.com/8482575/102219986-7e731600-3ee0-11eb-8f68-03c3aa8e08f0.png)

Here is what I suggest to do:
- refine the background mesh in *blockMeshDict*
```
vertices
(
    (-2.0 -2.0 -0.025)
    ( 5.0 -2.0 -0.025)
    ( 5.0  2.0 -0.025)
    (-2.0  2.0 -0.025)
    (-2.0 -2.0  0.025)
    ( 5.0 -2.0  0.025)
    ( 5.0  2.0  0.025)
    (-2.0  2.0  0.025)
);

blocks
(
    hex (0 1 2 3 4 5 6 7) (140 80 1) simpleGrading (1 1 1)
);
```
- *snappyHexMesh*
  - remove the *precisionBox*
  - set `maxGlobalCells 32000000;`
  - set the surface refinement to `level (6 6);`

Before starting the simulation, check if the layers were created correctly.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Instructions noted, will get back to you soon.
Thanks.

Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
I had an idea for improving the mesh quality at the trailing edge. We can use snappyHexMesh's feature refinement. You can implement it with the following steps:

- add a new *surfaceFeatureExtractDict* to the system folder with the following content
```
/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v2006                                 |
|   \\  /    A nd           | Website:  www.openfoam.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      surfaceFeatureExtractDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

naca0012-34.stl
{
    // How to obtain raw features (extractFromFile || extractFromSurface)
    extractionMethod    extractFromSurface;

    // Mark edges whose adjacent surface normals are at an angle less
    // than includedAngle as features
    // - 0  : selects no edges
    // - 180: selects all edges
    includedAngle       150;

    subsetFeatures
    {
        // Keep nonManifold edges (edges with >2 connected faces)
        nonManifoldEdges       no;

        // Keep open edges (edges with 1 connected face)
        openEdges       yes;
    }


    // Write options

    // Write features to obj format for postprocessing
    writeObj            yes;
}


// ************************************************************************* //
```
- add *surfaceFeatureExtract* to *runCase*
```
...
$runSerial ./transformGeometry $case
echo "Running surfaceFeatureExtract on " $case
$runSerial "surfaceFeatureExtract" $case &> ${case}log.surfaceFeatureExtract
echo "Running blockMesh on " $case
...
```
- add the following entry to the subsection *features* in *snappyHexMeshDict*
```
features
    (
        {
            file "naca0012-34.eMesh";
            level 7;
        }
    );

```

Following this strategy, you should get an increased refinement around the trailing edge. Therefore, you **won't** need another box for region refinement around the trailing edge. Let me know is the feature refinement improves the mesh quality.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Firstly, sorry for the late reply. Yes, I will definitely implement this. As per last discussion, I got the sign of surface layers around the airfoil surface, then I implemented the very small wake box at the trailing edge to improve the discontinuity there but unfortunately again I got the same error of terminating the simulation abruptly, so I thought this idea of addition of the small wake box is not working.

But thank you so much for your suggestion so that we can increase refinement at the TE. I will try this and let you know tomorrow.

Thanks.


Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I implemented the above instructions,  added _surfaceFeatureExtractDict _ and made other changes.

I am attaching the refinement screenshot at the TE of  airfoil after this implementations.
Also I will attach the log files of _snappyHexMesh_ and _surfaceFeatureExtractDict _  in the email.
Please have a look on it, suggest me any changes if needed.

Thank you.

Regards,
Tushar


![surfaceFeatureExtract](https://user-images.githubusercontent.com/71929988/102892029-8e9a7080-445f-11eb-9ecf-f6d0a6bb512a.png)

**Comment by AndreWeiner** [comment]
Switched from automatic to structured meshing approach with blockMesh.
