### ISSUE TITLE
Test of different inlet values for k and omega

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#15]
Hi Tushar,
I got feedback from a colleague that the inlet values for k and omega might be influencing the solution. In particular, high values for k might stabilize the solution too much. Therefore I suggest testing the following settings:

- take one case with the base mesh and fixed Re, Ma, and angle of attack
- vary k from a very small number, say 1.0E-5, up to the current one, which is about 320; the results for k=320 you already have; I suggest adding 3-4 cases with values in between
- the formula to compute omega you find [here](https://www.openfoam.com/documentation/guides/latest/doc/guide-turbulence-ras-k-omega-sst.html) in the section *Initialization*; for the mixing length L, take 5% of the chord length
- visualize the fields nut, k, omega and observe the difference

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

I got the instructions. One small doubt: Our chord length is 1. So I need to take 5% of 1 or the 5% of the scaling factor for L.
Please let me know.

Best,
Tushar

**Comment by AndreWeiner** [comment]
The chord length varies from case to case depending on the Reynolds number (see the blockMeshDict).

**Comment by Tushargh29** [comment]
Hello Sir,

When I was uploading the new cases on Phoenix by doing git pull there I got this error message which is attached below.
Could you please tell me what is this error exactly?
Thanks.
![Screenshot from 2021-01-25 16-54-38](https://user-images.githubusercontent.com/71929988/105730814-0f50fe80-5f2f-11eb-9bd2-fa45e3226790.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
you've created too much output and exceeded your quota (your available disk space). You can check your quota with `quota -s`
To perform further simulations, you have to free up some space, e.g., by deleting old or unsuccessful simulations (however, keep track of the parameters you already tested). You can also backup some simulations locally and move them back to the cluster if you want to continue.

To reduce the output in the first place, increase the write interval.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Small doubt:
   1.Suppose I want to change turbulence model in a hypothetical situation, if not k-omega and SA models,
which one would you suggest; shall I give a try for other k-omega models, for example: **k-kl-omega**, **Langtry-Menter k-omega Shear Stress Transport (SST)**? k-epsilon models are good for away from the wall so of no use for our case. 

2. Shall I consider further refining cases by modifying _blockMeshDict_ or those configurations for base and refined cases must be fixed from now onward?
 
Please give me your feedback.

Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
- keep the turbulence model for now
- keep the mesh unchanged for now

Best, Andre

**Comment by Tushargh29** [comment]
Sure sir.
Thanks

**Comment by Tushargh29** [comment]
Hello Sir,
Good Afternoon.

I created 5 cases where I varied the alpha from 4 to 9(excluding 5) and 5 cases where I varied the Reynolds number from 3 to 10 million.

But after 2 days of simulation, I am observing through gnuplot that every case is going steady and flat once again(not looking promising).

I think, now I will keep everything like that but will give a try for Mach no 0.87 or probably 0.80.

Please let me know what you think.

Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,

you haven't set the inlet velocity properly. Check, e.g., [this](https://github.com/Tushargh29/transonic_shock_buffet/blob/master/test_cases/naca-Re-3-Ma-0.85-base_alpha-9_k-0.00001/0.orig/U) case, which is supposed to be alpha=9. Executing the script to compute the inlet velocity vector yields:
```
[288.3753648   45.67417076]
8.999999999999943
```
However, your inlet velocity vector in U is:
```
Uinlet          (290.858966 25.44686221 0);
```
Stop the simulations, check and correct the settings, and restart the simulations.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thanks a lot for looking into the problem. Actually I realized where I was making a mistake, probably because of this I am not getting desired results.

Actually I will fix this ASAP, restart the simulation and let you know.

Best,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

After 2 days of simulation of the corrected cases, I observed this which I am attaching below.
This result is for: **naca-Re-3-Ma-0.85-base_alpha-4_k-0.00001** case.
Let me know what you think, I am doubtful that the time scale on x-axis is so small till now, so these fluctuations should not look flat on higher time scale. But, you please let me know. Shall I mail you the animation video?

Thank you.

Regards,
Tushar

![result_alpha-4](https://user-images.githubusercontent.com/71929988/106483325-ae857100-64ae-11eb-8705-a4f2ad6a4728.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
the lift coefficient signal looks promosing. Could you create an animation and upload it to the cloud storage?
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,
Yes, I uploaded the avi on cloud as well as in email.
Thanks.

Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I visualized the case which is going flat or steady so to say the velocity profile,
but fortunately I noticed the significant change in these two animations, flat case is not  showing any BL separation on the surface after some initial fluctuations.
I will forward the animation avi of another case of another unsuccessful case.
Please check this as well.
Thanks

**Comment by Tushargh29** [comment]
Hello Sir,

I will cancel the remaining simulation cases on cluster which are going steady, instead I am planning to do following:

1. The current setup is a base case, I can give a try for the same setup but with fine case.
2. I think buffet is somewhat sensitive to alpha, because the next alpha case which is 6 is going completely steady, may be I can try the same setup but changing alpha = 3.0 & alpha = 4.5, alpha = 4.5. Because in most of the survey papers, they got the buffet sign from 3 to 5.
3. Also, I can try a few cases varying Mach no from 0.83 to 0.87 and higher Reynolds numbers.

Please let me know your feedback.

Thanks.

Best regards,
Tushar

**Comment by AndreWeiner** [comment]
Alright, go ahead. I suggest keeping the k/omega values low since those simulations displayed a more sensible turbulent viscosity.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thanks for your confirmation.
Yes I  will keep the value of k unchanged (k = 0.00001).
See you tomorrow.

Best,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I started running the fine case of the above setup yesterday.
Today surprisingly,I noticed that the fine case is going flat after some initial fluctuations.
So may be I will perform rest of the cases on base setup will see what happens with these cases.
Thanks.
![res3](https://user-images.githubusercontent.com/71929988/106598045-843bbe00-6557-11eb-90f0-6f342e47107e.png)
