### ISSUE TITLE
Incorrect inlet velocity vector

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#16]
Hi Tushar,

I noticed in one of your setups that the inlet velocity vector is not set correctly. E.g. [here](https://github.com/Tushargh29/transonic_shock_buffet/blob/9341cc7b5290b2b596001e8446485e9d56c93a67/test_cases/naca-Re-10-Ma-0.85-base_alpha-5_k-0.00001/0.orig/U#L17), the inlet velocity has a non-zero z-component.

The *compute_inlet_velocity.py* script prints the x and y components of the velocity vector in square brackets. The value in the next line is the angle of attack and not the z-component (it's a consistency check). The z-component is always zero in our simulations.

Please check your simulations.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thanks for bringing this error in my attention. I will correct it ASAP and restart the simulations.
I will let you know soon the results.

Best,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

Just to give you an update,

I set up 11 new cases with the correction you suggested today.
8 cases: 3 Million, Ma-0.85, k=0.00001, base varying alpha from 0, 1, 2, 3, 3.5, 4, 4.5, 9
3 cases: 3 Million, Ma-0.85, k=0.00001, fine varying alpha from 3,3.5 and 4.

I will let you know what happens.
Thank you.

Best,
Tushar
