### ISSUE TITLE
Change fvSchemes

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#17]
Hi Tushar,

I may have found the issue with the setup. Please, try the following change in `fvSchemes`:

```
// current setting
    div(phiv,p)     Gauss upwind;
    div(phid,p)     Gauss upwind;
// new setting
    div(phiv,p)     Gauss limitedLinear 1.0;
    div(phid,p)     Gauss limitedLinear 1.0;
```
You **do not** have to stop your currently running simulations. OpenFOAM dictionaries are modifiable at runtime. You can:

1. login on the cluster
2. go to the *run* directory
3. for each running case
  3.1 open *system/fvSchemes*
  3.2 modify the two lines mentioned above and save the file
  3.3 move on to the next case

Let me know if this works for you.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thanks for the suggestion, yes I will definitely try it the way you just described above.
But If I make the changes now in the running cases, what about the already generated output time instants?
They are generated based on the previous setup.

Nevertheless, I will try it and let you know.
Thanks.


Regards,
Tushar

**Comment by Tushargh29** [comment]
Hi Sir,

I tried  to edit the file through geditor. But it is not displaying the file.
Do I need to edit this online on cluster or first need to sync the data in local repo and edit?
Please let me know.
Thanks.
![err](https://user-images.githubusercontent.com/71929988/106895763-ed0a6e00-66f0-11eb-90d5-ec70d64383c8.png)

**Comment by AndreWeiner** [comment]
You need to use a command-line editor.
- login on the cluster and navigate to a running case
- type `nano system/fvSchemes`
- change the two lines
- press `Ctrl+o`, then press `Enter`
- press `Ctrl+x`

**Comment by Tushargh29** [comment]
Thanks sir.
