### ISSUE TITLE
Comparison with experimental data for NACA0012 profile

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#19]
Hi Tushar,

I've created a pull request with a new setup. Changes are:

- improved blockMeshDict; have a look at the new mesh
- standard NACA 0012 airfoil
- files and options for Spalart-Allmaras turbulence model
- two function objects to compute and write the surface pressure coefficient

I suggest taking a step back. The article
> Reynolds-Averaged Navier–Stokes Study of the Shock-Buffet Instability Mechanism

contains comparisons of the surface pressure coefficient for pre-buffet and buffet conditions (standard NACA 0012 airfoil). To see how the new setup performs, I suggest the following steps:

- create the setups 1, 2, 4, 6 from table 1 in the article; consider the nominal angle of attack and Mach number (subscript N); keep the Reynolds number at 10^7 (current base setup)
- from [this article](https://ntrs.nasa.gov/api/citations/19850019511/downloads/19850019511.pdf), digitize the corresponding experimental data (1: page 23 (26 in the PDF); 2: page 29 (32 in the PDF); 4: page 43 (46 in the PDF); 6: page 55 (58 in the PDF)); tables lower and upper airfoil surface; columns X/C and C_P
- run the simulations until steady-state; you can take the lift or drag coefficient as a reference
- compare the pressure coefficient between experiment and simulation
  - C_P in the simulation is written to *postProcessing/surfaces/*
  - load both the experimental and numerical data in a jupyter notebook and plot them comparatively
  - typically, -C_P (negative) is plotted over the length coordinate instead of C_P
  - the x-coordinate should be normalized with the chord length such that x in [0, 1]
  - the plots should look similar to the ones in figure 1 of the article mentioned above

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thanks for the detailed instructions. I understood the taskpoints.
I will start the work now and let you know the results very soon.
Thanks.

Best regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

One small doubt:

The current base case is (_naca0012-Re-10-Ma-0.75-alpha-4-SA_) in addition to this I should create 4 more cases based on  set1, set2, set4 and set 6 given in table1 of the article. 

So, in total I should run 5 cases on cluster.
Please correct me if I am wrong.

Could you please tell me why are we running cases from **prebuffet configuration (table1)** even though we have the data for the **shock-buffet configuration (table 2)**.

Thanks.

Best,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
please, run only cases 1, 2, 4, and 6. The idea is to first validate the setup under conditions for which we have local reference data (the pressure coefficients). If the results for pre-buffet conditions look good, we move on to the buffet conditions.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Yes, I understood now.
Thanks.

Best,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I have digitized the experiment data from the graphs for set1, set2, set4 and set6.
You please have a look on it. Suggest me corrections if any.
Thanks.

Best,
Tushar

![Airfoil surface pressure coefficient (Experimental) for dataset-1](https://user-images.githubusercontent.com/71929988/107242535-5f9a8700-6a2c-11eb-834b-d447ebf0a318.png)
![Airfoil surface pressure coefficient (Experimental) for dataset-6](https://user-images.githubusercontent.com/71929988/107242540-61644a80-6a2c-11eb-89be-8332298f38a5.png)
![Airfoil surface pressure coefficient (Experimental) for dataset-2](https://user-images.githubusercontent.com/71929988/107242549-62957780-6a2c-11eb-8c05-2a8635ea73ce.png)
![Airfoil surface pressure coefficient (Experimental) for dataset-4](https://user-images.githubusercontent.com/71929988/107242554-63c6a480-6a2c-11eb-85e7-e4c068c01ce8.png)

**Comment by AndreWeiner** [comment]
Good job Tushar. The font size of the axis labels and the title could be a little smaller but otherwise, the plots look nice.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,
Thanks. I will reduce the font size of axis labels and title.
Best,Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I submitted all 4 jobscripts for 4 sets  successfully also jobIDs got created.
But when I am checking the jobs in queue it is showing only 1 job in queue.
What happened to other 3 jobs?

Why did it happen like that?

Best,
Tushar
![error3](https://user-images.githubusercontent.com/71929988/107271119-12c6a880-6a4c-11eb-8c15-1e7293860a6f.png)

**Comment by AndreWeiner** [comment]
Have a look at the log files of rhoPimpleFoam of the cases that crashed. I set the maximum Courant number to 2. Maybe you have to change it back to one for the cases in question.
```
# in system/controlDict
# ...
maxCo           1.0;
```
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Actually I changed the Courant number from 2 to 1 for suspicious cases. Still it is terminating abruptly.
It has something to do with processes exiting with non zero code. Last time,  this happened because of some incorrect setting of the case and it was giving such instability in the solution but that time it was a problem of meshing.

![error4](https://user-images.githubusercontent.com/71929988/107285447-78706000-6a5f-11eb-9d03-5ec816f6cfca.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
two suggestions:
- in `system/fvSolution` set the solver tolerance to 10^-6 instead of 10^-7
```
    "(rho|U|k|omega|e|epsilon|R|nuTilda)"
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-6;
        relTol          0.1;
    }
```
- check again if the setup is correct in terms of Re, Ma, and alpha

If that doesn't work, upload the log-files to the cloud storage and I have a look.
Best, Andre

**Comment by Tushargh29** [comment]
Thanks Sir.
I changed the solver tolerance to 10^-6. I let the simulations running for sometime.
Right now, Set1 and Set6 are running properly.
Set2 and Set4 got terminated again.
I have uploaded the log files of all 4 cases on cloud, have a look.

Best, Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
I couldn't find a quick fix for cases 2 and 4. Probably, it will be necessary to initialize the flow with rhoSimpleFoam. For now, focus on the working cases.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Okay. I agree.
Thanks 

Best,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

When I observed the set6 data, I found still less output time steps are generated because it was 15 hours delayed while starting compared to set1, its Cl graph still showing big fluctuations(not steady yet). 

So I think I should wait for today's time and plot the comparison for both sets tomorrow. Meantime I will to figure out the script of comparison(normalizing and all).

Thanks.

Best,
Tushar

![set1](https://user-images.githubusercontent.com/71929988/107511303-9647dd00-6ba5-11eb-9407-d4d353be8fa1.png)
![set6](https://user-images.githubusercontent.com/71929988/107511313-9811a080-6ba5-11eb-8c8c-7c1ef157c6e2.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
simply take the last available time folder for now. Case 6 looks interesting, and it definetly needs more time.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Small doubts:

1. Earlier I had csv files for experimental data so it was easy to plot.
Now numerical data is in .raw file format. Now, I am confused; shall I first convert raw file to csv file and then plot? or directly try to plot from raw file. What should be the correct approach to this ? Does using Jupyter Notebook will make any difference here?

2. Also, when it comes to normalizing the x coordinates that means all the values in the first (x) column should be multiplied by (1/ scaling factor) and this new column I need to plot against the cp values right? 
Please correct me If I am wrong. 

Thanks.

Best,
Tushar

**Comment by AndreWeiner** [comment]
You can read and plot the data as follows:
```
import pandas as pd
import matplotlib.pyplot as plt

path="path_to_raw_file"
data = pd.read_csv(path, sep=" ", skiprows=[0, 1], header=None, names=["x", "y", "z", "cp"])
# normalize x
data.x = data.x / data.x.max()
# split in lower and upper side
data_up = data[data.y >= 0]
data_low = data[data.y < 0]
# plot example
plt.plot(data_up.x, data_up.cp)
plt.show()
```

**Comment by Tushargh29** [comment]
Hello Sir,

I was using exactly the same command but I was wrong for using _usecols_;
**ab = pd.read_csv("total(p)_coeff_airfoil.raw", sep="\t", usecols=['x'])**
**cd = pd.read_csv("total(p)_coeff_airfoil.raw", sep="\t", usecols=['total(p)_coeff'])**

But I am glad that atleast my approach was somewhat correct.
Anyway, thanks a lot for the correction.

I will get back to you with the plots soon.
Thanks.

Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

In the morning I noticed the remaining 2 cases of set1 and set6 got terminated unfortunately.
I have uploaded the log files on cloud.
The set1 is showing this till the latest time.

Regards,
Tushar
![acc](https://user-images.githubusercontent.com/71929988/107638811-5dc10580-6c70-11eb-9920-4aaebb9f4c60.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
there is no error in the log files. I guess the simulations were terminated because your allocated runtime on the cluster finished. Simply restart the simulations. Please, plot C_p against the experimental data. Can you also provide the C_l curve for cases 1 and 6?
Best, Andre

**Comment by Tushargh29** [comment]
Yes sir, I will restart the simulation. Also, I will plot the graph of comparison.
(Just need confirmation: for restarting from the latest time I need to comment the two lines where we copy the run folder in the jobscript, is anything more than that required?)
For now here are the Cl graphs for set1 and set6 respectively.
Thanks.
![aaaa](https://user-images.githubusercontent.com/71929988/107641936-864afe80-6c74-11eb-8aba-ca418eb4ab8d.png)
![bbbbb](https://user-images.githubusercontent.com/71929988/107641946-8945ef00-6c74-11eb-8b1e-f80730f76632.png)

**Comment by Tushargh29** [comment]
Sorry sir, I clicked the wrong button by mistake.

**Comment by Tushargh29** [comment]
Hello Sir,

One small doubt:
I noticed after 18 hours of restarted simulation, the output time steps are still that only, generated by previous terminated simulation, so when I am trying to sync data in local repo, no new data is there. But simulation is going for last 18 hours, by this time it should have generated a couple of outputs, but it is still 0.195(terminated simulation latest time).

What would be the reason? I checked the output in the cluster run folder but there I found the same, then where the simulation output of the restarted one is getting saved? I am confused.

Please have a look at my jobscript for restarted one:
![jjjj](https://user-images.githubusercontent.com/71929988/107756392-725ed580-6d24-11eb-8360-cfd8b2696b27.png)
Do I need to do something else apart from this change in jobscript specifically for restarting simulation from the latest time?
Please let me know.

Thanks

Best,Tushar

**Comment by AndreWeiner** [comment]
Tushar,
have a look at your [own post](https://github.com/Tushargh29/transonic_shock_buffet/issues/14#issuecomment-763585227). You restarted the simulation from scratch. On the cluster, run `tail -f log.rhoPimpleFoam` to see the current simulation time. Escape the tail command by pressing Ctrl+c
Best, Andre

**Comment by Tushargh29** [comment]
Thanks Sir.
I got the thing. 
But, it is interesting to see specially for set6 which is a case of prebuffet, giving strong oscillations and also visualized the velocity field in paraview, it is showing much stronger flow separation than the previous cases.

Best,
Tushar

**Comment by AndreWeiner** [comment]
That sounds interesting. Let's see if the oscillatory motion persists.

**Comment by Tushargh29** [comment]
Hello Sir,
As per our today's discussion, I have done plotting of graphs of comparison for Set1 and Set4.
Please have a look at it.
Let me know your feedback.
Thanks.

![set1](https://user-images.githubusercontent.com/71929988/108214567-98271880-7130-11eb-8536-3343c3fd5575.png)
![set4](https://user-images.githubusercontent.com/71929988/108214572-99f0dc00-7130-11eb-902e-6dcd7eaca264.png)

**Comment by AndreWeiner** [comment]
Thanks for the update. To make the plots a bit more comprehensible, could you
- distinguish between lower and upper surface
- plot the numerical data as line plot
- give the markers of the upper side the same color as the line; the same for the lower surface

Best, Andre

**Comment by Tushargh29** [comment]
Okay, I will do this.
Thanks

**Comment by Tushargh29** [comment]
Hello Sir,
Have a look at the plots.
Suggest corrections, if required.
Thanks.
Tushar
![adadad](https://user-images.githubusercontent.com/71929988/108260979-464bb600-7163-11eb-876f-dfd606e7c925.png)
![fssfsf](https://user-images.githubusercontent.com/71929988/108260984-48157980-7163-11eb-999f-03a72c86b42d.png)

**Comment by Tushargh29** [comment]
Or maybe this:
Same markers for upper and lower surfaces(experimental) but with different colors.
Thanks.
Tushar
![hhhhh](https://user-images.githubusercontent.com/71929988/108261577-1d77f080-7164-11eb-9727-aa9e996bd9e4.png)
![rrrr](https://user-images.githubusercontent.com/71929988/108261580-1ea91d80-7164-11eb-9116-2bb61a538617.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
the results don't look too bad I would say. Next, it is important to check for the dependency on the mesh resolution and the discretization. Here are a couple of suggestions:
- visualize yPlus the same way as you did for Cp above; surface samples of yPlus are available in the same file as Cp; probably, you'll have to fix the range of the y-axis in your plot due to the high values at the trailing edge, e.g., `ax.set_ylim(0.0, 10.0)`
- increase only the tangential resolution:
```
    xUCells 320;  // upstream
    xMCellsLower 280; // middle low
    xMCellsUpper 280; // middle up
    xDCells 400; // downstream
```
- increase only the grading normal to the surface:
```
yGrading       40000;
```
- if the simulations with increased grading do not work, increase both tangential resolution and grading at the same time
- for the original mesh and the mesh with refinement in tangential direction only, test the following two divergence schemes:
  - linearUpwind
```
divSchemes
{
    default         none;

    div(phi,U)      Gauss linearUpwindV limited;

    turbulence      Gauss linearUpwind limited;
    energy          Gauss linearUpwind limited;

    div(phi,k)       $turbulence;
    div(phi,omega)   $turbulence;
    div(phi,nuTilda) bounded Gauss linearUpwind limited;

    div(phi,e)      $energy;
    div(phi,K)      $energy;
    div(phi,Ekp)    $energy;

    div(phiv,p)     Gauss linearUpwind limited;
    div(phid,p)     Gauss linearUpwind limited;

    div(((rho*nuEff)*dev2(T(grad(U)))))    Gauss linear;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
    div(((rho*(thermo:mu|rho))*dev2(T(grad(U))))) Gauss linear;
}
```
  - vanLeer
```
divSchemes
{
    default         none;

    div(phi,U)      Gauss vanLeerV;

    turbulence      Gauss vanLeer;
    energy          Gauss vanLeer;

    div(phi,k)       $turbulence;
    div(phi,omega)   $turbulence;
    div(phi,nuTilda) bounded Gauss vanLeer;

    div(phi,e)      $energy;
    div(phi,K)      $energy;
    div(phi,Ekp)    $energy;

    div(phiv,p)     Gauss vanLeer;
    div(phid,p)     Gauss vanLeer;

    div(((rho*nuEff)*dev2(T(grad(U)))))    Gauss linear;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
    div(((rho*(thermo:mu|rho))*dev2(T(grad(U))))) Gauss linear;
}
```
In total, there should be 6 new simulations if everything works out.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,
I need your confirmation on 2 things:

1. This is the Cl distribution for dataset1; here graph is going steady, currently **endTime = 1** is set up, considering the margin I am planning to set **endTime = 0.5 or maybe 0.4**. Would it be sensible to do?
![sample](https://user-images.githubusercontent.com/71929988/108512950-31d1ff80-72c2-11eb-95a3-259fac5962f2.png)



2. Here I have plotted the yPlus distribution for dataset1; I am not sure whether it is correct or not, because I have not seen the yPlus distribution of an airfoil unlike Cp distribution so that I can imagine. What do you think about this yPlus graph, one thing to notice for sure is; yPlus values are so high at TE.
![sample2](https://user-images.githubusercontent.com/71929988/108513193-8a090180-72c2-11eb-9e68-a22b6f4c3c86.png)

Please let me know your feedback.
Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,

- 0.5s should be fine
- for yPlus: please read the post above more carefully; use `ax.set_ylim(0.0, 10.0)` to make the plot more comprehensible

Best, Andre

**Comment by Tushargh29** [comment]
Thanks Sir,

Yes, Initially I set up _ax.set_ylim(0.0, 10.0)_ but then values were going out of bound so I changed to 120 to see what happens.
As per your instructions it is like this:
![sample3](https://user-images.githubusercontent.com/71929988/108514995-dead7c00-72c4-11eb-9a31-dba3b74c7af6.png)


Best,
Tushar

**Comment by AndreWeiner** [comment]
Note that most likely, yPlus < 1 needs to be fulfilled for the entire surface to get good results (except for the trailing edge).
The increased grading I suggested might not be enough, but let's have a look at the results first.
Best, Andre

**Comment by Tushargh29** [comment]
Yes sir, I understood.
Let's see what happens with the new simulations.
I will let you know the results soon.
Thanks

Tushar

**Comment by Tushargh29** [comment]
Hello Sir,
Just to give you an update:

1. I have created 12 cases, 6 cases for dataset1 and dataset4. 
2. Dataset6 is still running very very slow(original case), So I did not run its 6 cases on cluster, rather I am running the original case again from the latest time.
3. Out of above 12 cases, 10 cases are running fine(all cases of set1) but for set4, 2 cases are constantly getting terminated those are **Original_vanLeer** and **increasedTangentialResolution_vanLeer**, I tried to decode the error message in the log file twice, but could not get it. It would be great if you have a look at it. I will upload these files on cloud.

Please let me know what you think.
Thanks.

Best regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
I can't see from the log files where the problem might be. Just ignore the two cases for now.
Best, Andre

**Comment by Tushargh29** [comment]
Okay sir

**Comment by Tushargh29** [comment]
Hello Sir,

The combined Cp distribution graph as per your instruction is like this.
But it is so crowded and not comprehensible, I think if I use same color for both upper and lower surface then it might be helpful.
Nevertheless, you correct me.
Thanks.

![sampleee](https://user-images.githubusercontent.com/71929988/108920239-9da2c800-7634-11eb-8de4-a8bb0c6e8493.png)

**Comment by AndreWeiner** [comment]
Dear Tushar,

some further information on the IDDES setups:
- an endTime of 0.25 is sufficient
- a grading factor of 10000 gave me good results
- there are some oscillations around the shock; maybe setting maxCo back to one improves the results

You should get something similar to the following picture for the lift coefficient of set 1 at 4 degrees angle of attack
![lift_set1_alpha4](https://user-images.githubusercontent.com/8482575/111288875-e1418e00-8644-11eb-9cd0-c1c9a57d7ad8.png)


Best, Andre
