### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#2]
Hi Tushar,

to get familiar with the workflow and the simulation setup, here are some tasks to get on track:

- merge the pull request
- follow the instructions in the README file to run your first simulation
- while the simulation is running, use `tail -f log.rhoPimpleFoam` to follow the solver output inside the simulation folder; you can interrupt the simulation or the output of *tail* using **Ctrl+C**
- open the airfoil geometry in ParaView and take a look: `paraview test_cases/naca0012-34-base/constant/triSurface/naca0012-34.stl`
- add a file called *naca_simulation_setup.md* to the repository and create a list of all files in the setup; create a short description of the files' purpose; if you're uncertain, try to find a description online or post open questions in this issue; for basic Markdown syntax, see [here](https://www.markdownguide.org/basic-syntax/)

Best, Andre

**Comment by Tushargh29** [comment]
Respected Sir,

I noted all your instructions.
Yes, I will definitely take a look at all the stuff from this and your
previous email.
If needed, I will contact you.

I will start this work from tomorrow onwards.
Thank you.
Stay Safe.

Best Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

In the last task point, we already created a read-me file in today's session. I understood that I should include the short description about the purpose of each file contained in the setup.

My question is the word "files" includes only log files or every file which is present along with the log files for example files present in the folders like "0", "constant", "system", "processor0", etc?

**Comment by AndreWeiner** [comment]
Hi Tushar,
please make the description only for the basic, clean setup (not the executed simulation). Consider also the files in sub-folders.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Understood. To give you the further update, the simulation got finished, I received the output for the time instances from 0.001 to 0.146.

I will complete the last task point as soon as possible.
Thank You.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

As per your instruction, I have completed the remaining task point which is nothing but creating a readme.md file describing the purpose of all files included in the basic simulation setup.

Please have a look on it and suggest me the changes if needed.

Thank you.


Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
great job creating the case description. I've added some additional comments to the [commit](https://github.com/Tushargh29/transonic_shock_buffet/commit/8864b8af91d057c4cd6f1d526c8388261e1f5e6c). Once they are included in the description, the first issue is completed.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

I made the necessary changes in the readme.md file as per your suggestion.
Please have a look and let me know your suggestions.

Thank you.

Best Regards,
Tushar
