### ISSUE TITLE
Trial of OnSet-Buffet cases

### ISSUE THREAD

**Issue by Tushargh29** [Tushargh29/transonic_shock_buffet#20]
Hello Sir,

As per our discussion, I created the onset cases for dataset1 and started running the simulations on cluster.
The cases are as follows:
1. Case1: OnSet_Set1_Ma-0.75_Re-10Mio_GaussLinear_alpha-4_OriginalMesh
2. Case2: OnSet_Set1_Ma-0.75_Re-10Mio_GaussLinear_alpha-4_FineMesh
3. Case3: OnSet_Set1_Ma-0.75_Re-10Mio_GaussLinear_alpha-6_OriginalMesh
4. Case4: OnSet_Set1_Ma-0.75_Re-10Mio_GaussLinear_alpha-6_FineMesh

I am changing the Courant number after some time interval as well to accelerate the simulations.
I will plot the Cp, Cl and yPlus distribution graphs for onset as well as prebuffet cases very soon.
Thanks.

Best,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
don't go beyond maxCo=4 because my tests with Co=8 got terminated.
Best, Andre

**Comment by Tushargh29** [comment]
Okay sir. I will change till maxCo=4 only.
Thanks.
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,
If I am not wrong I need to change this maxCo on cluster cases using the nano command only right?
Because cases are still very slow and transient also not worth to plot, so want to confirm whether I did changes correctly or not.
Thanks.

Tushar

**Comment by AndreWeiner** [comment]
Yes, you can use nano to edit the controlDict of the running simulations.

**Comment by Tushargh29** [comment]
Thanks sir.
Then I did changes correctly till maxCo=4.
Then, I will wait for today's time for the curves to become somewhat flat.
I will give you update after plotting.

Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

Till this moment, the Cp and yPlus distribution graphs for Original, Intermediate and Fine mesh are as follows:
The Cl curves are still transient not steady.

![Figure_111](https://user-images.githubusercontent.com/71929988/110210288-405b1200-7e91-11eb-9a9c-4c1f499ef97f.png)
![Figure_1222](https://user-images.githubusercontent.com/71929988/110210289-4224d580-7e91-11eb-870c-15dfab84bbb0.png)


Cl curve for intermediate yGrading:
![ClGrad1](https://user-images.githubusercontent.com/71929988/110210308-58cb2c80-7e91-11eb-8323-23915dab04dc.png)

Cl curve for fine yGrading:
![ClGrad2](https://user-images.githubusercontent.com/71929988/110210330-6d0f2980-7e91-11eb-8956-c9de548007ba.png)


Nevertheless, I have restarted all the simulations (prebuffet and onset) from the latest time.
I will plot these comparison graphs again on Monday, hopefully by that time curves will get somewhat flat.

yPlus values of intermediate mesh is around one; for fine mesh it is around 0.5, I did zooming and get to know the actual dimensions.

Thank you.

Best regards,
Tushar

**Comment by Tushargh29** [comment]
Hi Sir,

I have plotted the graphs of comparison for Cp and yPlus distribution.
But, unfortunately I have not seen much changes in the graphs in comparison to what I posted above.

Thanks.
Tushar
![bbbbbbbb](https://user-images.githubusercontent.com/71929988/110338320-281cfb80-8027-11eb-9341-557dc9b07209.png)
![aaaaa](https://user-images.githubusercontent.com/71929988/110338328-29e6bf00-8027-11eb-9a2b-52c7c3da89a1.png)

**Comment by AndreWeiner** [comment]
Dear Tushar,
at what time do you plot the cp distribution?
Best, Andre

**Comment by Tushargh29** [comment]
Hi Sir,

Do you intend to say the time folder data after syncing the output ?
I have generated this graphs like always, from the latest time folders available after syncing the output data of all 3 cases.
Thanks.

Tushar

**Comment by AndreWeiner** [comment]
Dear Tushar,
I am asking for the physical time corresponding to the latest output of each case.
Best, Andre

**Comment by Tushargh29** [comment]
Hi Sir,

I plotted these graphs approx an hour ago.

The physical time corresponding to the latest output of each case:
Intermediate mesh case (Gauss Linear): 0.135
Fine mesh case(Gauss Linear): 0.065
Fine + Linear Upwind: 0.045

Tushar

**Comment by AndreWeiner** [comment]
What about the "original" data?

**Comment by Tushargh29** [comment]
Oh sorry sir, I forgot to mention that case.
Here it is,
Original case (only increased tangential resolution and Gauss Linear): 0.055
Intermediate mesh case (Gauss Linear): 0.135
Fine mesh case(Gauss Linear): 0.065
Fine + Linear Upwind: 0.045

Tushar
