### ISSUE TITLE
Implementing IDDES approach for NACA0012 airfoil

### ISSUE THREAD

**Issue by Tushargh29** [Tushargh29/transonic_shock_buffet#22]
Hello Sir,

As per your instructions in the pull request, I started cases of 2D and 3D setup based on IDDES approach.
I will let you know the results of the simulation soon.
Thanks.

Best regards,
Tushar

**Comment by Tushargh29** [comment]
https://github.com/Tushargh29/transonic_shock_buffet/issues/19#issuecomment-800110855

Hello Sir,
Thanks for the suggestion.
Yes, I will do these changes ASAP.

1. I will change the endTime of running cases to 0.25.
2. 10000 is nothing but yGrading factor I assume, which is currently 40000.
3. I will change to maxCo=1.
4. I will create two more cases for 2D and 3D setup each for alpha=4.

I will observe the changes and results in today's and tomorrow's time. Then, we can discuss results in tomorrow's meeting.

Best regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

As per our last discussion, I have done sensitivity analysis of the base case by varying some of the parameters for dataset-1. 

The following simulation cases I created and ran on Phoenix for both **prebuffet** and **onset** conditions:
1. Base case (default tangential resolution and yGrading = 10000).
2. Only decreased yGrading= 5000.
3. Only increased tangential resolution.
4. Combined case of  increased tangential resolution plus decreased yGrading.
5. Decreased yGrading plus linear upwind scheme.
6. No Wall Functions (basecase).

 In addition to this, 2 cases of 3D setup which were there already.
So, in total I run **14** simulation cases on Phoenix.

Currently, all the cases are over.
I would like to point out something:
1. Out of 6 cases for each prebuffet and onset condition, only 3 cases successfully completed their simulation till endTime. These 3 cases are: **basecase**, **only decreased yGrading** and **no Wall Functions (basecase)**.
2. **Only increased tangential resolution** case setup failed after a few hours of running for both conditions; I checked the log files, but nothing was wrong there. The same thing goes with **Combined case of  increased tangential resolution plus decreased yGrading** case setup.
3. Then, **Decreased yGrading plus linear upwind scheme** case setup failed to give fluctuations for the onset condition, Cl curve was totally flat; no sign of buffet in Paraview. This observation again underlined that in our case **Gauss limitedLinear** scheme is promising than any other scheme. I was just trying to see what happens with the linear upwind scheme.
4. Finally, both cases of 3D setup are running very very slow, cannot plot Cp distribution, so I did not pay much attention on these 3D setups, focused more on 2D setups.

When it comes to changing the parameters to see if we are getting even better results than that of the  basecase; I think, **decrease in yGrading** criteria is appropriate because other case setups got terminated and I cannot see any error in the log files.


Thanks.

Best regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

Now, I have plotted the Cp distribution and yPlus distribution graphs for prebuffet condition and roughly calculated the reduced frequencies for onset condition and compared with the value given in the table-2 of 2012 article for dataset-1.

Reduced frequencies casewise:
1. **basecase** : 0.75
2. **only decreased yGrading** : 0.77
3. **no Wall Functions (basecase)** : 0.76

I have calculated these frequencies just by measuring the time period of the wave. Actually, the experimental frequency of dataset-1 for onset condition is given as 0.47 in the table and here we are getting some deviation in the values for simulations. 

Also,
Please have a look at the graphs:
![Cp_distribution_all3](https://user-images.githubusercontent.com/71929988/112060702-d2d00680-8b5d-11eb-87dd-2668791de813.png)
![Cp_dist_base_vs_decyGrad](https://user-images.githubusercontent.com/71929988/112060718-d5caf700-8b5d-11eb-9917-f90f5ffa2022.png)
![yPlus_dist_all3](https://user-images.githubusercontent.com/71929988/112060731-d95e7e00-8b5d-11eb-9de5-247ec0e69d96.png)


I will send you the animation videos of all above mentioned 3 cases where results are promising.
See you on Wednesday.

Thank you.

Best regards,
Tushar

**Comment by AndreWeiner** [comment]
Dear Tushar,

thanks for the update. Make sure to document your observations in your report. Regarding the c_p distribution above, are you sure that the base case reached the final simulation time? I would be also interested to know why the simulations with increased tangential resolution crashed. I have performed several such simulations without any problems. I suggest checking the setup and the last iterations in the log file.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

1. Yes the base case has reached the endTime of 0.5 and I plotted the Cp graphs from the latest time folder.
2. Yes, I will check the log files and setup of increased tangential resolution to see what went wrong, probably put the new cases again on cluster.
3. Yes, I have noted down all these observation to include in the final report.
See you tomorrow.

Thanks.

Best,
Tushar
