### ISSUE TITLE
Compute estimate for cell-width at airfoil surface

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#3]
Hi Tushar,

currently, the basic setup uses wall-functions to correct *mu*, *k*, and *omega* at the airfoil surface. Ideally, we would like to avoid the usage of wall functions because they introduce uncertainty to our simulation (we don't know how well assumptions made in derivation apply to our case). To see if it is feasible to resolve the boundary layer down to *yPlus=1*, it is useful to make an estimate for the necessary cell-width at the airfoil surface:

1. Follow [this procedure](https://www.cfd-online.com/Wiki/Y_plus_wall_distance_estimation) to compute an estimate for the cell-width; report also intermediate results; you can use [this syntax](https://stackoverflow.com/questions/11256433/how-to-show-math-equations-in-general-githubs-markdownnot-githubs-blog) to render Latex formulas
2. check the *yPlus* field using *paraview*; select only the *airfoil* patch; report the *yPlus* values around the thickest part of the airfoil; get an estimate for the width of the first cell layer (load internal mesh; pick one cell that is roughly horizontal; use the *extractSelection* filter; look at the bounds in the *information* tab)
3. Compare the current cell-width with the width estimated in 1.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

For calculation of Reynold's number, we need freestream velocity, rho, characteristic length and mu.
Out of that, I got the values of U,mu. But could you please tell me how to find the values of rho and L?

Also, U is a vector field, do I need to put only 1st non zero component in the reynold formula?

Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,

- for the freestream density, have a look at the [README.md](https://github.com/Tushargh29/transonic_shock_buffet/blob/master/test_cases/naca0012-34-base/README.md) file; the density is implicitly defined by mol-weight, pressure, and equation of state
- the characteristic length of an airfoil is typically the [chord length](https://en.wikipedia.org/wiki/Chord_(aeronautics)); for most geometry files, the chord length is simply set to unity; in the OpenFOAM simulation, the mesh, and therefore the chord length, is scaled by a given factor to adjust the Reynolds number; the scaling factor is defined in the *Allrun* script
- the Reynolds number is a scalar value computed using a characteristic velocity; if you have an inlet velocity vector, you would typically use the magnitude

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Please find the report on the tasks given in issue #3. Let me know your feedback and changes if any.

Thank you.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
good job computing the resolution estimate. I get a slightly different Reynolds number when I plug your values into the calculator. The setup was originally designed to yield Re=3.0E6. The round-off error may cause a small deviation. I suggest you use sientific notation the next time (e.g., 1.0E-5 instead of 0.00001). Anyhow, the estimate is close enough.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thank you so much. I will update the scientific notations for the values immediately.

Later, have a look on it.

Best Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

As per your instruction, I made necessary changes in the notations of values.

Thanks.

Regards,
Tushar
