### ISSUE TITLE
Extract reference data for drag and lift

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#4]
Hi Tushar,

in [1], you find reference data for drag and lift coefficients of the airfoil investigated in this project:
- Fig 175 on page 284 provides drag coefficients for varying angle of attack and Mach number
- Fig 161 on page 274 provides lift coefficients for varying angle of attack and Mach number

To work with the reference data,
- extract the measurements using [digitizer](http://markummitchell.github.io/engauge-digitizer/) or a similar tool; after this step, you should have two or more textfiles holding the numerical values for drag and lift
- re-create the original plots using Python (the plots don't have to look exactly the same; only the provided information should be the same); Matplotlib is a great package to create visualizations; Pandas or Numpy can help you to load the data

Get in touch if you need help :-)
Best, Andre

[reference 1](https://books.google.de/books/about/Theory_of_Wing_Sections_Including_a_Summ.html?id=DPZYUGNyuboC&redir_esc=y)

**Comment by Tushargh29** [comment]
Hello Sir,

As per your instruction, I have included all the data files and scripts required to implement issue #4.

- Please find all these files in [extracting_the_reference_data](https://github.com/Tushargh29/transonic_shock_buffet/tree/master/extracting_the_reference_data) folder which I created for this issue as there were a lot of files to be included.

- Also, I have written a task report on this issue #4 as usual, please find this here: [Reference_data_extraction_report_issue#4.md](https://github.com/Tushargh29/transonic_shock_buffet/blob/master/extracting_the_reference_data/Reference_data_extraction_report_issue%234.md).

Please have a look on it.
Let me know any change if needed.

Happy Sunday.


Best Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

As per your instruction, I have changed the scripts and the report.
Please have a look on it here: [extracting_the_reference_data](https://github.com/Tushargh29/transonic_shock_buffet/tree/master/extracting_the_reference_data) also the report: [Reference_data_extraction_report_issue#4.md](https://github.com/Tushargh29/transonic_shock_buffet/blob/master/extracting_the_reference_data/Reference_data_extraction_report_issue%234.md).

Please let me know any changes and suggestions if needed.

Thank you.

Best regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
the plots look fine. There still seem to be too many points in the extracted data files. If you compare the scatter plot markers with the markers in the original plot, the number of markers should be equal. Another tip: the axis-labels appear a bit small; you can change the font size as follows:
```
fontsize_label = 20
# ...
ax.set_xlabel(r"$x$", fontsize=fontsize_label)
```
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,
Please have a look on the following images and let me know if still some refining is required, this time measured every point (example: There are always 15 points for every alpha curve). Likewise I tried to extract. Nevertheless, let me know your feedback.

Thank you.
![Figure_1](https://user-images.githubusercontent.com/71929988/96741126-cb93a980-13c1-11eb-91ca-671f4cce20e9.png)
![Figure_2](https://user-images.githubusercontent.com/71929988/96741143-ce8e9a00-13c1-11eb-951e-71c338cb50f7.png)

**Comment by Tushargh29** [comment]
Hello Sir,

One more thing, I tried to log in to Phoenix cluster, first I tried to connect to the TUBS VPN, but it showing error there only. 
It is not identifying my y-number as username.

Just have a look on it.
![Screenshot from 2020-10-21 23-13-20](https://user-images.githubusercontent.com/71929988/96788192-5fca3480-13f3-11eb-83a0-4cd0dd5af8b0.png)

Please suggest.

Thank you.


Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
next time, please open a new issue since this problem is unrelated to the extraction of reference data.
The steps to connect to the vpn server are:
1. initiate the connection to the vpn using openconnect
2. select a group: `Tunnel-All-Traffic`
3. enter your y-number
4. enter your password

Best, Andre

**Comment by AndreWeiner** [comment]
Hi @Tushargh29 ,
there are still too many extracted data points. There should be exactly 15 points per reference curve. Therefore, the file exported from digitizer should have exactly 16 lines (one line for the header). I think you have to extract each line into a separate file. After the extraction, you should have files like:
```
cd_alpha_0.csv
cd_alpha_1.csv
....
```
Each file should have exactly 16 lines. Then you load and plot the individual files. Use the *point match tool* to select the experimental data points, and let me know if this solves the problem.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

1. Actually I observed that there are some data points which are thick dark completely filled circles not symbols like square, triangle or rectangle, when I am selecting such spots, automatically digitizer is generating more data points which are totally useless and the plots representing same unnecessary points as well.

2. Nevertheless, this is actually a good idea to extract data points curve-wise and saving in separate .csv files and then recreating the plots.

3. I will do this now and let you know the results.

4. Should  I use **point match tool** instead of **Digitizer**?. Is that doing the same thing?

Thank you.


Regards,
Tushar

**Comment by AndreWeiner** [comment]
I created a short screencast to demonstrate how to do it: [link](https://cloudstorage.tu-braunschweig.de/getlink/fiEocwJfZCh2gVwEp3kAuhz9/digitizer_example-2020-10-22_14.09.08.mp4)

**Comment by Tushargh29** [comment]
Okay Sir,
Understood.
I will get back to you with the results soon.
Thank you.

**Comment by Tushargh29** [comment]
Hello Sir,

- Please have a look on the revised plots, this time I checked each _.csv_ file using _cat_ command whether they are having **16** points or not.
- Now every curve is having distinct 15 points.
- Let me know your feedback.
- If everything is okay then allow me to push the changes in the remote repository.

Thank you.

![Cd_plot](https://user-images.githubusercontent.com/71929988/96928172-7b4b4300-14b8-11eb-964d-171815d2029f.png)
![Cl_plot](https://user-images.githubusercontent.com/71929988/96928181-7dad9d00-14b8-11eb-9b96-cbf69501cd4b.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,
the plots are fine for now. You can push the changes, and I'll close the issue.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Changes are pushed to the remote repository.
Thank you.

Best regards,
Tushar
