### ISSUE TITLE
Perform test simulation on Phoenix

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#6]
Hi Tushar,
please, try to follow [these instructions](https://github.com/darshan315/flow_past_cylinder_by_DRL/issues/14#issuecomment-715040907) to perform a first test simulation on Phoenix. Let me know if you need more detailed instructions. You can also get in touch with Darshan since he is working currently on a similar step.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Instructions noted.
Thank you.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

After login in TUBS VPN , I was trying to connect with and log in Phoenix.

But several times I am getting this message with denied access, do I need to something more to get that access?. 
I am putting my y-number credentials only.

Please let me know.

Thanks.

Regards,
Tushar
![Screenshot from 2020-10-27 10-54-07](https://user-images.githubusercontent.com/71929988/97285706-d2e40880-1842-11eb-88ec-fc2449182180.png)

**Comment by Tushargh29** [comment]
Hello Sir,

I want to list down the steps from what I understood in the Darshan's issue:

1. First I need to run singularity + MPI .
2. Then, I need to create a **jobscript** file in _.sh_ format and mention all the commands to run the simuation of test case.
3. Then, I need to submit this job file using the command given in the comment section.
4. Then I understood the theory of creating a jobscript which includes implementation of both preprocessing and executing the solver in parallel. But could not understand its later part in the comment sections.

Please let me know where I am making mistake in logging in Phoenix so I can try first three steps and get back to you immediately.

Thanks

Best,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
here are the updated instructions:
- Github: accept pull request; have a close look at the modifications
- local: update repository
- local: build singularity image (see README)
- phoenix: `git clone https://github.com/Tushargh29/transonic_shock_buffet.git`
- local (replace user_name): `scp of2006-py1.6-cpu.sif user_name@phoenix.hlr.rz.tu-bs.de:/home/user_name/transonic_shock_buffet/`
- phoenix (in transonic_shock_buffet folder): `sbatch jobscript`
- phoenix - check that your simulation is running: `squeue -u user_name`

Let me know if this works for you.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,
Instructions noted.

I will get back to you soon. 
Thanks

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,
I tried to update the local repository by doing this:
First, I accepted 2 pull requests>git clone> my branch was up to date.

But If I am looking at the files to see the modifications, it is still showing the old file content, new changes have not reflected there.

What is the reason?
Is there any other way to update the local repository?

I built the singularity successfully.

Let me know your reply.
Thanks,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
the online version of your repo is up-to-date. The command to update your repository locally is `git pull` and not `git clone`.
Best, Andre

**Comment by Tushargh29** [comment]
Sorry, I meant git pull only but not git clone.
My bad.
Anyway Something was going wrong. I did refresh, now everything is updated locally also.

Thanks 
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,
after successfully running the commands given by you today in the morning,

I checked whether the simulation is running on Phoenix using _squeue_ command and it shows this:
![Screenshot from 2020-11-10 20-50-09](https://user-images.githubusercontent.com/71929988/98726482-dde87e00-2396-11eb-83f1-0d3df42628d9.png)

Does this mean, our simulation task is on waiting or something on Phoenix? or simulation is done(I don't think so)?
How to interpret this?

Thank you.

Regards,
Tushar

**Comment by darshan315** [comment]
Hi Tushar,

- `JOBID` - Id of your job.
- `NAME` - the name of your job on the cluster.
- `USER` - your user id with a cluster.
- `ST` - status of your job. `R` means Running and `PD` means pending.
- `TIME` - the time of your simulation running on the cluster.

If the simulation is done then you would not have a job description in `squeue`. In `squeue` you have the job information that is running on the cluster at that time. you can see that by auto-generated slurm output by `cat slurm_name`. To cancel the running process: `scancel "JOBID"`

Best Regards,
Darshan.
