### ISSUE TITLE
Literature review

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#7]
Goal:
Create a literature review concerned with the numerical simulation of buffeting at NACA0012(-34) and similar airfoils. Information of interest might be:

- investigated range in terms of Reynolds and Mach number as well as the angle of attack; conditions for buffeting
- type of turbulence modeling, e.g, RAS, LES, hybrid
- turbulence model
- application of wall modeling
- mesh type (block-structured, unstructured) and mesh resolution
- 2D or 3D simulation

There are some sources in the shared cloud folder to start with. A good strategy might be to investigate the cited articles and to look at newer articles citing the article in question.

**Comment by Tushargh29** [comment]
Hello Sir,

Task noted.
Thank you.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I studied the resources provided by you and I tried to gather the information.

Can we have a small 10-15 minutes Skype meeting in the afternoon?

Just let me know.
Thanks 

Best Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I have created a markdown file for the report on the literature review.
You please take a look on it [here](https://github.com/Tushargh29/transonic_shock_buffet/blob/master/Literature_Review.md) specially the table format.

Suggest me any changes in the table format or anything related to it. This is just a trial table, if you allow me to go ahead I will add all the papers in it else I will make the changes now and then add.

Is there anything to add or remove in that report

Let me know your feedback.

Thank you.


Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

Please take a look at the revised report [here](https://github.com/Tushargh29/transonic_shock_buffet/blob/master/Literature_Review.md) and let me know your feedback.
Anything to add or change the format, etc
Thanks.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
good start! Could you also first author and year to the link, e.g., [Miller et al. 2003](link to article) instead of [Link](link to article). Were all the authors you listed able to reproduce the buffeting effect numerically? [Here](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/various-approaches-to-determine-active-regions-in-an-unstable-global-mode-application-to-transonic-buffet/9B82E8E5E3ABD88CA14B223C11A7BBE9) is another good resource listing quite a few articles. Maybe it is already on your list.
Best, Andre

**Comment by AndreWeiner** [comment]
Hi Tushar,
[this](https://www.tu-braunschweig.de/fileadmin/Redaktionsgruppen/Forschung/FOR1066/Veroeffentlichungen/SWNS_2012/5-Illi-2012.pdf) article seems to be of interest since buffet simulations are performed on unstructured meshes (maybe also the references therein).
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Yes sure, I will include the author names and the year in the report. Yes, all the papers which I included in the report have successfully achieved the prediction of transonic shock buffet, in fact these papers performed different cases of turbulence models, numerical schemes, alpha range, Re no, etc but I have chosen only the best cases which authors concluded on correct prediction of the buffet phenomenon numerically out of all the  cases.

Thanks for the listing additional resources, I will study this also, the report is not complete yet, I am listing quite a few cases which deal with the WMLES and Hybrid simulations to predict the buffet. I will update the report with all the cases very soon.


Thank you.


Best regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

Please take a look on the final report on the Literature review. [here](https://github.com/Tushargh29/transonic_shock_buffet/blob/master/Literature_Review.md)
Let me know the changes or addition if required.

Thank you.

Best regards,
Tushar

**Comment by AndreWeiner** [comment]
Looks good for now!
